version: '3.1'

services:
  db_linkshort:
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_DATABASE: 'linkshort_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'linkshort_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
