#!/bin/bash
# Passare unico parametro dominio da certificare
# ./crea-certificato www.dominio.local
# verranno generati i file .key e .crt necessari nella directory corrente
if [ $# == 1 ]; then
  openssl req -x509 -out $1.crt -keyout $1.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj "/CN=$1" -extensions EXT -config <( \
  printf "[dn]\nCN=$1\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:$1\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth");
else
  echo "aggiungere il parametro dominio";
fi
